// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"RED_ElementsFix","status":true,"description":"v1.04 A simple plug-in designed to adjust the sprite draw of Time Elements characters","parameters":{}}
];
