// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"RED_ElementsFix","status":true,"description":"v1.04 A simple plug-in designed to adjust the sprite draw of Time Elements characters","parameters":{}},
{"name":"EffekseerForRPGMakerMZ_Ex","status":true,"description":"Effekseer Extended plugin v1.60 - 1.01","parameters":{"InstanceMaxCount":"10000","SquareMaxCount":"10000","DistortionEnabled":"false"}}
];
