//=============================================================================
// Tal_Quests
// Tal_Quests.js
//=============================================================================


//=============================================================================
/*:
* @target MZ
* @plugindesc [RPG Maker MZ] [Tal_Quests]
* @author Tal
* @url https://tal.gg
*
* @help
* ============================================================================
* Integrates quests generated by OpenAI into the game
* ============================================================================
*
* @command startQuest
* @text Start a Quest
*
* @arg hash
* @text Quest Hash
* @type text
*
* @command goToRoom
* @text Go to Room
* @desc Go to a room in the generated dungeon
*
* @arg roomId
* @text Room ID
* @type string
*
* @arg x
* @text X
* @type number
*
* @arg y
* @text Y
* @type number
*/

(function() {
  const $pluginName = 'Tal_Quests';

  const initGamePlayerMembers = Game_Player.prototype.initMembers;
  Game_Player.prototype.initMembers = function() {
    initGamePlayerMembers.call(this);
    this._talQuestHash = '';
  }

  Game_Player.prototype.isInQuest = function() {
    return typeof this._talQuestHash === 'string' && this._talQuestHash.length > 0;
  }

  PluginManager.registerCommand($pluginName, "startQuest", ({ hash }) => {
    if ($gamePlayer.isInQuest()) {
      return false;
    }
    $gamePlayer._talQuestHash = hash;
    return true;
  });

  PluginManager.registerCommand($pluginName, "goToRoom", ({ roomId, x, y }) => {
    if (!$gamePlayer.isInQuest()) {
      return;
    }
    const mapName = [$gamePlayer._talQuestHash, roomId].join('/');
    SceneManager._scene.fadeOutAll();

    $gamePlayer.reserveTransfer(mapName, x, y, 2, 0);
    $gamePlayer.requestMapReload();

    SceneManager.sceneStartCallback = () => {
      $gamePlayer.locate($gamePlayer._x, $gamePlayer._y);
    }
  });

})();
